export const MESSAGE = {
  USER_CREATED_SUCCESS: "User created successfully.",
  USER_GET_SUCCESS: "User get successfully.",
  USER_ALREADY_EXISTS: "User already exists.",
  USER_NOT_EXISTS: "User not exists.",
  LEAD_CREATED_SUCCESS: "Lead created successfully.",
  USER_UPDATED_SUCCESS: "User updated successfully.",
  LEAD_UPDATED_SUCCESS: "Lead updated successfully.",
  LEAD_NOT_EXISTS: "Lead not exists.",
  EMAIL_SENT_SUCCESS: "Email sent successfully.",
  PASSWORD_VALIDATION_FAILED:
    "Password must contain at least one uppercase letter, one lowercase letter and one number.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  LOGIN_SUCCESS: "Login successfully.",
  FORGOT_PASSWORD_SENT: "Forgot password link sent successfully.",
  PASSWORD_RESET_SUCCESS: "Password reset successfully.",
  PASSWORD_RESET_LINK_EXPIRED: "Password reset link expired.",
  USER_PASSWORD_UPDATED: "User password updated successfully.",
  PASSWORD_SAME: "New password must be different from old password.",
  USER_DELETED_SUCCESS: "User deleted successfully.",
  LEAD_DELETED_SUCCESS: "Lead deleted successfully.",
  LEAD_DETAIL_SUCCESS: "Lead detail get successfully.",
  LEAD_LIST_SUCCESS: "Lead list get successfully.",
  
};